### ISSUE TITLE
Display block not detected

### ISSUE THREAD

**Issue by notPlancha** [acarapetis/mathjax-for-reddit#4]
![image](https://github.com/acarapetis/mathjax-for-reddit/assets/31565873/25759b4a-aead-411e-bbd1-c74e2274a714)

Turns into 

![image](https://github.com/acarapetis/mathjax-for-reddit/assets/31565873/f0e02de1-4f52-4965-9abc-e17bcfb03dd9)

while 

![image](https://github.com/acarapetis/mathjax-for-reddit/assets/31565873/f4045511-e397-4f6a-b7bc-2ea66b7f853e)

turns into

![image](https://github.com/acarapetis/mathjax-for-reddit/assets/31565873/f192d006-3bdf-4cb3-bc53-050c4e3e1f83)

The console yields this

![image](https://github.com/acarapetis/mathjax-for-reddit/assets/31565873/1656b037-6499-476f-8755-37679534ba27)

The same yields for inline formatting. Using fresh new chrome.

**Comment by acarapetis** [comment]
documentation was incorrect; display math actually requires `[(; ... ;)]`. See #5.
